### ISSUE TITLE
Support running operator in Docker for Mac with Apple Silicon

### ISSUE THREAD

**Issue by dougsparling** [FoundationDB/fdb-kubernetes-operator#986]
Hello! First off, I realize that between the layers of virtualization for docker and emulation of amd64, this probably isn't a wise idea, but I figured it was worth asking in case it's an easy fix.

Basically I tried running the operator on an M1 Mac two different ways:
1. Docker for Mac's built-in Kubernetes support
2. Minikube using the docker driver + Docker for Mac

Both reported the same error during reconciliation:
`FoundationDB error code 1510 (Disk i/o operation failed)`

A quick search suggested that this was due to a limitation of Docker for Mac which could be overcome by setting the `knob_disable_posix_kernel_aio=1` knob as a custom parameter. However, this didn't work. I tried running `fdbcli` inside one of the pods to get more information, and that actually failed with the same disk I/O error. Suspecting that maybe the operator was trying and failing to get status information via `fdbcli`, I patched the operator to set this knob on `fdbcli` too. And that helped!

But then I ran into a new error:

`FoundationDB error code 2009 (Network can be configured only once)`

Searching for this error yielded nothing relevant but a hit inside the FDB source itself, which was beyond my ability to troubleshoot. 

Perhaps the "solution" here might be to just wait for ARM builds of FoundationDB itself, but I couldn't help trying to get it working anyway.

Thanks!

**Comment by johscheuer** [comment]
I'm not sure about the setup of Docker for Mac running on an M1 and I don't have one to test this setup. I only can refer to the FoundationDB issue https://github.com/apple/foundationdb/issues/4111 with FDB's missing support, which is probably linked.

If you want need the FDB binaries for arm (on Linux) please open an issue in the FoundationDB repository, AFAIK FDB supports arm on Linux and we just don't publish images build for arm.

Once you figure out how to run the operator/FDB on a M1 or in general on an arm based system I would appreciate a PR with the docs for thee setup :)

**Comment by dougsparling** [comment]
Interestingly enough the macOS package from the website (6.2.30) worked out of the box for me on Rosetta. Running the foundationdb image directly with docker run also works, albeit with a hacked entrypoint script (fdb.bash) to pass the knob to the  `fdbserver`.

Given this limited success, I figured it made sense to open the issue here and not on the main FDB repo, since it might just be some weird edge case the operator hits that my other testing didn't.

If FDB already supports linux+arm then it might be possible for me to build and test that with the operator; I'll give that a shot when I have a bit more time. And if I do find success, I'd be happy to open a PR, but I wouldn't bet on it :she

**Comment by johscheuer** [comment]
Could you share the FoundationDB cluster spec you used? The default config (for testing) already sets the knob: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/config/tests/base/cluster.yaml#L39-L42 so hat should be working.

**Comment by dougsparling** [comment]
I could clean up and share my cluster spec, but I tried again after resetting the docker VM, and then with the sample operator deployment and the test cluster above with the knob set, and the result is similar.

First I get a couple of these errors, presumably from fdbcli itself failing, since the knob is set correctly on the server process: 
```
{
  "level": "error",
  "ts": 1637199476.321004,
  "logger": "controller",
  "msg": "Error in reconciliation",
  "namespace": "default",
  "cluster": "test-cluster",
  "subReconciler": "controllers.updateStatus",
  "requeueAfter": 0,
  "error": "FoundationDB error code 1510 (Disk i/o operation failed)",
  "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/FoundationDB/fdb-kubernetes-operator/controllers.processRequeue\n\t/workspace/controllers/controllers.go:114\ngithub.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBClusterReconciler).Reconcile\n\t/workspace/controllers/cluster_controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:99"
}
```

And then this error repeats indefinitely:
```
{
  "level": "error",
  "ts": 1637241741.0974813,
  "logger": "controller-runtime.manager.controller.foundationdbcluster",
  "msg": "Reconciler error",
  "reconciler group": "apps.foundationdb.org",
  "reconciler kind": "FoundationDBCluster",
  "name": "test-cluster",
  "namespace": "default",
  "error": "FoundationDB error code 2009 (Network can be configured only once)",
  "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:302\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:99"
}
```

So at least it isn't something odd with my local config.

So there seem to be two issues: one is that fdbcli fails (because the knob isn't set there), and then this error code 2009.

Building that arm64 image of FDB is still on my todo list!

**Comment by johscheuer** [comment]
If the error happens, that would mean the `fdbcli` is not able to write the log files. You could try our to pass the `--knob_disable_posix_kernel_aio=1` knob to our fdbcli command. For a quick verification if that is actually the issue you could add that know here: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/fdbclient/admin_client.go#L158 and deploy the newly build version with `SKIP_TEST=1 make rebuild-operator`. It's still interesting that the cli is failing without that knob, since the cli should only be writing log files 🤔 For the `"Reconciler error"` could you share a few log lines before that error happens? There should be a log line `"Attempting to run sub-reconciler"` to indicate what sub-reconciler sees that issue. I would guess that this issue comes either also from `fdbcli` or the fdb library/client itself when we try to get the FoundationDB cluster status.

**Comment by dougsparling** [comment]
Ah, actually your suggestion is the first thing I tried 😄 With that tweak applied to the latest operator and deploying the default testing config, the cluster still fails to reconcile with the network error.

I've attached the entire log up to the point of failure, but I think the relevant bit is that the `updateDatabaseConfiguration` sub-reconciler is being run:

```
{
  "level": "info",
  "ts": 1637364504.2924135,
  "logger": "controller",
  "msg": "Attempting to run sub-reconciler",
  "namespace": "default",
  "cluster": "test-cluster",
  "subReconciler": "controllers.updateLabels"
}
{
  "level": "info",
  "ts": 1637364504.293459,
  "logger": "controller",
  "msg": "Attempting to run sub-reconciler",
  "namespace": "default",
  "cluster": "test-cluster",
  "subReconciler": "controllers.updateDatabaseConfiguration"
}
{
  "level": "info",
  "ts": 1637364504.293604,
  "logger": "fdbclient",
  "msg": "Fetch status from FDB",
  "namespace": "default",
  "cluster": "test-cluster"
}
{
  "level": "error",
  "ts": 1637364504.2939308,
  "logger": "controller",
  "msg": "Error in reconciliation",
  "namespace": "default",
  "cluster": "test-cluster",
  "subReconciler": "controllers.updateDatabaseConfiguration",
  "requeueAfter": 0,
  "error": "FoundationDB error code 2009 (Network can be configured only once)",
  "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/FoundationDB/fdb-kubernetes-operator/controllers.processRequeue\n\t/workspace/controllers/controllers.go:114\ngithub.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBClusterReconciler).Reconcile\n\t/workspace/controllers/cluster_controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:99"
}
```

[logs-failed.txt](https://github.com/FoundationDB/fdb-kubernetes-operator/files/7573404/logs-failed.txt)

**Comment by johscheuer** [comment]
Yeah, the log statement shows what I suspected. The operator fails in the `fdbclient` during the `Fetch status from FDB` step where we directly use the go client. Could you try setting that know in the client like described here: https://pkg.go.dev/github.com/apple/foundationdb/bindings/go/src/fdb#NetworkOptions.SetKnob I think the simplest way is to set the knob here https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/fdbclient/common.go#L48 (we will set the knob multiple times if we create a new DB but that should be fine, since we only want to prove in the first plave that this is the issue).

Thanks for your time!

**Comment by dougsparling** [comment]
Your suggestion was definitely on the right track, although one extra step was needed: I also had to change the version of FDB installed when building the operator's image to 6.3.9, which is the earliest version where [this fix](https://github.com/apple/foundationdb/issues/2382) is present.

After doing this, the operator seemed to run normally, but then all the cluster's pods got stuck in a crash loop. Further inspection revealed this error from fdbmonitor:

`Unable to initialize inotify (inotify_init error 38: Function not implemented)`

Which happens because QEMU doesn't support inotify. I scanned the source briefly and it doesn't look like inotify is really needed in this case, since I think the operator itself handles config changes anyway... but there's no knob to disable it. Perhaps hacking the FDB source and rebuilding the image to omit it is the logical next step, or trying to build an ARM-native image to avoid the inotify limitation.

**Comment by johscheuer** [comment]
This is probably blocked until FDB releases an arm64 version of the libraries.

**Comment by johscheuer** [comment]
In https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1975 I added some more details on this issue. I would close this issue as there is nothing to change in the operator right now. Once arm64 binaries and libraries are available we will update the docs.
